### ISSUE TITLE
[BUG] Node v19 cause issue with project starting and story book

### ISSUE THREAD

**Issue by Junaid300** [DouyinFE/semi-design#1287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. I cloned the project and run commands as explained in contributor file
2. I had node version 19
3. When i ran command npm run bootstrap and got this error
```
> semi@0.0.1 start
> npm run story


> semi@0.0.1 story
> npm run pre-story && start-storybook -c ./.storybook/js/ -p 6006


> semi@0.0.1 pre-story
> lerna exec --scope=@douyinfe/semi-ui --scope=@douyinfe/semi-foundation -- rimraf ./lib && lerna run build:lib --scope @douyinfe/semi-webpack-plugin --scope eslint-plugin-semi-design

lerna notice cli v3.22.1
lerna notice filter including ["@douyinfe/semi-ui","@douyinfe/semi-foundation"]
lerna info filter [ '@douyinfe/semi-ui', '@douyinfe/semi-foundation' ]
lerna info Executing command in 2 packages: "rimraf ./lib"
lerna success exec Executed command in 2 packages: "rimraf ./lib"
lerna notice cli v3.22.1
lerna notice filter including ["@douyinfe/semi-webpack-plugin","eslint-plugin-semi-design"]
lerna info filter [ '@douyinfe/semi-webpack-plugin', 'eslint-plugin-semi-design' ]
lerna info Executing command in 2 packages: "yarn run build:lib"
lerna info run Ran npm script 'build:lib' in 'eslint-plugin-semi-design' in 2.4s:
yarn run v1.22.19
$ rm -rf lib && tsc
Done in 2.28s.
lerna info run Ran npm script 'build:lib' in '@douyinfe/semi-webpack-plugin' in 2.6s:
yarn run v1.22.19
$ rimraf lib && tsc
Done in 2.48s.
lerna success run Ran npm script 'build:lib' in 2 packages in 2.7s:
lerna success - eslint-plugin-semi-design
lerna success - @douyinfe/semi-webpack-plugin
info @storybook/react v6.4.22
info 
if you want to get cypress code coverage, set TEST_ENV=test, now it is 'undefined'
info => Loading presets
(node:23994) DeprecationWarning: You have specified an invalid glob, we've attempted to fix it, please ensure that the glob you specify is valid. See: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Using implicit CSS loaders
info => Using default Webpack4 setup
(node:23994) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
10% building 1/7 modules 6 active ...a11yHighlight.js-generated-config-entry.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/junaidklair/github.com/semi-design/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/junaidklair/github.com/semi-design/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/junaidklair/github.com/semi-design/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/junaidklair/github.com/semi-design/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/junaidklair/github.com/semi-design/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/junaidklair/github.com/semi-design/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/junaidklair/github.com/semi-design/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/junaidklair/github.com/semi-design/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /home/junaidklair/github.com/semi-design/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.1.0


```
4. i am using nvm to switch node version so i switched to v14.16 and i start working fine
```
nvm use v14.17.3
Now using node v14.17.3 (npm v6.14.13)
```
Still there are some deprecation warning. It should be great if we configure it with node nearer versions

### Environment

```markdown
- OS: UBUNTU 22 LTS
- browser: Firefox
- node: v19.1.0
- nvm: 0.39.2
- npm: v6.14.13
```

**Comment by pointhalo** [comment]
The reason: https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382
node use OpenSSL 3.0 since v17,  so when webpack createHash it will throw error https://github.com/webpack/webpack/issues/14532

can set  `--openssl-legacy-provider` as a temporary workaround. 

```
    "start": "NODE_OPTIONS='--openssl-legacy-provider --inspect' npm run story",
```
