### ISSUE TITLE
[BUG] Next.js 使用 Modal 组件从 2.56.2 升级 2.63.0 报错

### ISSUE THREAD

**Issue by czn574775237** [DouyinFE/semi-design#2380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Semi Version

2.63.0

### Current Behavior

在 nextjs 处于开发编译的情况下，报如下错误，似乎升级后某个别组件不兼容 SSR 的环境，直接使用 document 导致报错？ 在 2.56.2 版本的使用是正常的。

```bash
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (/Users/chenzhining/Developer/apps/ai-search/ui/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/chenzhining/Developer/apps/ai-search/ui/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/chenzhining/Developer/apps/ai-search/ui/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/chenzhining/Developer/apps/ai-search/ui/.next/server/webpack-runtime.js:33:43)
    at eval (./app/cms/application/[id]/page.tsx:9:75)
    at (ssr)/./app/cms/application/[id]/page.tsx (/Users/chenzhining/Developer/apps/ai-search/ui/.next/server/app/cms/application/[id]/page.js:359:1)
    at Object.__webpack_require__ [as require] (/Users/chenzhining/Developer/apps/ai-search/ui/.next/server/webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
digest: "1589295105"
```

### Environment

```markdown
- OS: MacOs 14.5
- browser: Edge 127.0.2651.74
```

**Comment by czn574775237** [comment]
我尝试了升级了几个版本，发现2.56.2升级到 2.61.0 的版本，Nextjs 14.3 开发编译都是正常的，然后从 2.61.0 升级到 2.62.1 则有问题了，把这2个标签的版本代码对比后发现确实有一个代码似乎有问题。

https://github.com/DouyinFE/semi-design/compare/v2.61.0...v2.62.1?diff=split&w=#diff-5423660e3dbf640a98e9af46c7f13b69528345bb35d8af786d6db86f16abb295

![image](https://github.com/user-attachments/assets/72ff10bd-eefb-4f01-8088-34e2cb2a110f)

```tsx
render() {
        const {
            maskClosable,
            className,
            getPopupContainer,
            maskFixed,
            getContainerContext,
            ...rest
        } = this.props;
        const { direction } = this.context;
        const classList = cls(className, {
            [`${cssClasses.DIALOG}-popup`]: getPopupContainer && getPopupContainer() !== document.body && !maskFixed,
            [`${cssClasses.DIALOG}-fixed`]: maskFixed,
            [`${cssClasses.DIALOG}-rtl`]: direction === 'rtl',
        });
}
```

大概是 Nextjs  SSR 运行到 render() 这一步 访问到 document.body 这里报错了  @pointhalo

**Comment by pointhalo** [comment]
get.
@DaiQiangReal  cc，与 PR https://github.com/DouyinFE/semi-design/pull/2335 改动相关

**Comment by pointhalo** [comment]
![image](https://github.com/user-attachments/assets/56ddfe97-ca36-4d17-b45a-087902ed1a91)

fix  2.64.0-beta.0

**Comment by czn574775237** [comment]
我对比以为只有 `Modal.tsx` 组件，但实际上似乎不仅仅那个问题，我这里给出一个完整的示例，那个 document undefine 的问题依然存在
```json
"dependencies": {
    "@douyinfe/semi-ui": "2.64.0-beta.0",
    "next": "14.2.5",
    "react": "^18",
    "react-dom": "^18"
  }
```
我新建了一个全新的项目，使用的 nextjs App router 页面路由，页面还是报错了
```tsx
"use client";

import React from "react";
import { Form, Button } from "@douyinfe/semi-ui";
// import { authApiService } from "@/api/auth";

const authApiService = {
  login: async (data: any) => {
    return await fetch("/api/auth/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => res.json());
  },
};

type FormState = {
  username: string;
  password: string;
};
export default function AuthLoginPage() {
  const handleSubmit = async (values: FormState) => {
    try {
      const res = await authApiService.login(values);
      const token = res.data.data.token;
      localStorage.setItem("token", token);

      window.location.href = `/embed/chat`;
    } catch (ex) {}
  };
  return (
    <div className="mx-auto max-w-[500px] mt-[100px] border rounded-lg shadow-lg p-8">
      <Form
        onSubmit={(values: FormState) => handleSubmit(values)}
        style={{ width: 400 }}
      >
        <Form.Input
          field="username"
          label="账号/工号"
          style={{ width: "100%" }}
          placeholder="Enter your empl number"
        ></Form.Input>
        <Form.Input
          field="password"
          label="密码"
          style={{ width: "100%" }}
          type="password"
          placeholder="Enter your password"
        ></Form.Input>

        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <Button htmlType="submit" type="tertiary">
            登录
          </Button>
        </div>
      </Form>
    </div>
  );
}
```

```bash
GET /favicon.ico 200 in 12ms
 ✓ Compiled in 720ms (6016 modules)
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at eval (./app/page.tsx:9:75)
    at (ssr)/./app/page.tsx (/home/zhining/my_apps/test-app/.next/server/app/page.js:228:1)
    at Object.__webpack_require__ [as require] (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
digest: "3315334200"
 GET / 500 in 150ms
 ✓ Compiled in 958ms (6016 modules)
 GET /favicon.ico 200 in 509ms
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at eval (./app/page.tsx:9:75)
    at (ssr)/./app/page.tsx (/home/zhining/my_apps/test-app/.next/server/app/page.js:228:1)
    at Object.__webpack_require__ [as require] (/home/zhining/my_apps/test-app/.next/server/webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
digest: "3315334200"
 GET / 500 in 137ms
```

**Comment by czn574775237** [comment]
> ![image](https://private-user-images.githubusercontent.com/88709023/355432730-56ddfe97-ca36-4d17-b45a-087902ed1a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODk2NDMsIm5iZiI6MTcyMjk4OTM0MywicGF0aCI6Ii84ODcwOTAyMy8zNTU0MzI3MzAtNTZkZGZlOTctY2EzNi00ZDE3LWI0NWEtMDg3OTAyZWQxYTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwMDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTlhMTY0MGFhNmQ5YzVlNjc4MGM3NzgxY2ZhMjU2YjVhMGIxMjY2YTdiZWQwNTdlMmVhMWNlMzNlMzgzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFXjnVvbaX7WblLrGrUmFIYrt-wwqhtxfmIg5ypX0qc)
> 
> fix 2.64.0-beta.0

问题还是存在，我查看 2.61.0 对比 2.62.0 对比引入了3个新的组件，是否有可能是因为主入口引入的3个新组件的基础引入导致报错了
