### ISSUE TITLE
[BUG] Chat组件Uncaught runtime errors:ResizeObserver

### ISSUE THREAD

**Issue by algfwq** [DouyinFE/semi-design#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Chat

### Semi Version

2.63.1

### Current Behavior

运行官网的演示代码，出现的报错：
Uncaught runtime errors:
×
ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:199272:58)
    at http://localhost:3000/static/js/bundle.js:199291:7
![屏幕截图 2024-07-29 215705](https://github.com/user-attachments/assets/08d61f86-c777-4453-8836-de1de224c518)

### Expected Behavior

不显示该报错

### Steps To Reproduce

运行官网演示代码

### Environment

```markdown
- OS:Windows11 24H2
- browser:Edge 127.0.2651.74
```

### Anything else?

[eslint]
src\Chat.js
  Line 2:16:   'Radio' is defined but never used                                                                                         no-unused-vars
  Line 75:28:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\Chat.js
  Line 2:16:   'Radio' is defined but never used                                                                                         no-unused-vars
  Line 75:28:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps

webpack compiled with 1 warning

**Comment by YyumeiZhang** [comment]
我这边官网没有复现你的问题。给个 codesandbox 复现示例？录屏看看详细复现路径

**Comment by algfwq** [comment]
> 我这边官网没有复现你的问题。给个 codesandbox 复现示例？录屏看看详细复现路径

代码仓库：https://github.com/algfwq/Semi_worry
Codesandbox：https://codesandbox.io/p/github/algfwq/Semi_worry/master?import=true

**Comment by algfwq** [comment]
> 我这边官网没有复现你的问题。给个 codesandbox 复现示例？录屏看看详细复现路径

录屏链接：https://www.123pan.com/s/KIfoTd-3LQ0d.html

**Comment by algfwq** [comment]
> 我这边官网没有复现你的问题。给个 codesandbox 复现示例？录屏看看详细复现路径

请尝试拨动选项卡
![image](https://github.com/user-attachments/assets/4cabc9e4-8219-4b8b-be38-be951fc4df44)

**Comment by Feyily** [comment]
+1，我也遇到了这个问题
react版本：18.3.12
semi版本：2.72.1

**Comment by Feyily** [comment]
+1，我也遇到了这个问题

react版本：18.3.12
semi版本：2.72.1

**Comment by fnknzzz** [comment]
如果 chrome 没有复现可以试试 safari，safari 可以稳定复现

**Comment by YyumeiZhang** [comment]
<strong>问题原因：</strong>
Chat 组件的输入部分使用了 TextArea 组件（设置了 autosize） 属性， 因此有上面的  ResizeObserver loop completed with undelivered notifications 的报错。

使用了 autosize 属性的 TextArea 中有用到 ResizeObserver 监听
https://github.com/DouyinFE/semi-design/blob/v2.72.0/packages/semi-ui/input/textarea.tsx#L319
value 变化时候，会计算实际的高度 https://github.com/DouyinFE/semi-design/blob/v2.72.0/packages/semi-ui/input/textarea.tsx#L144

高度变化时候，会触发 ResizeObserver 的 onResize 调用，调用的函数链中有 https://github.com/DouyinFE/semi-design/blob/v2.72.0/packages/semi-foundation/input/textareaFoundation.ts#L197 语句，导致在<strong>开发</strong>中报错ResizeObserver loop completed with undelivered notifications。

<strong>问题的影响范围</strong>
该问题仅会在开发环境下报错，在线上环境中不会出错。

<strong>是否需要修改？</strong>
不需要修改，ResizeObserver 中监听容器变化，计算合适的高度是必要的逻辑。
