### ISSUE TITLE
[BUG] cloudflare remix框架模板下报错

### ISSUE THREAD

**Issue by favoritewky** [DouyinFE/semi-design#2444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

所有

### Semi Version

2.64.0

### Current Behavior

 cloudflare remix框架模板下报错

```
Unexpected token ':'
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (Y:\ffb\software\ffbmaster-web\node_modules\@douyinfe\semi-ui\lib\cjs\index.js:618:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async nodeImport (file:///Y:/ffb/software/ffbmaster-web/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52954:15)
    at async ssrImport (file:///Y:/ffb/software/ffbmaster-web/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:16)
    at async eval (Y:/ffb/software/ffbmaster-web/app/routes/_index.tsx:4:31)
    at async instantiateModule (file:///Y:/ffb/software/ffbmaster-web/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:5
```

### Steps To Reproduce

yarn create cloudflare
>frameworkstart
>remix

直接加载组件就报错了。
官方文档说了 https://remix.run/docs/en/main/start/future-flags#vite-plugin
要去除
Remove @remix-run/css-bundle

Vite has built-in support for CSS side effect imports, PostCSS and CSS Modules, among other CSS bundling features. The Remix Vite plugin automatically attaches bundled CSS to the relevant routes.

The [@remix-run/css-bundle](https://remix.run/docs/en/main/styling/bundling) package is redundant when using Vite since its cssBundleHref export will always be undefined.

👉 Uninstall @remix-run/css-bundle

npm uninstall @remix-run/css-bundle

👉 Remove references to cssBundleHref

- import { cssBundleHref } from "@remix-run/css-bundle";
  import type { LinksFunction } from "@remix-run/node"; // or cloudflare/deno

  export const links: LinksFunction = () => [
-   ...(cssBundleHref
-     ? [{ rel: "stylesheet", href: cssBundleHref }]
-     : []),
    // ...
  ];

和semi的官方文档冲突了，请问该怎么解决？

### ReproducibleCode

```markdown
import type { MetaFunction } from "@remix-run/cloudflare";
import {Button} from "@douyinfe/semi-ui";

export const meta: MetaFunction = () => {
  return [
    { title: "New Remix App" },
    {
      name: "description",
      content: "Welcome to Remix on Cloudflare!",
    },
  ];
};

export default function Index() {
  return (
   <>
     <Button>123</Button>
   </>
  );
}
```

### Environment

```markdown
- OS:windows
- browser:
edge
```

**Comment by favoritewky** [comment]
请问这个普通vite配置是指引入semi的插件吗还是？方便给个简单样例吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月29日 15:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DouyinFE/semi-design] [BUG] cloudflare remix框架模板下报错 (Issue #2444) |

remix v2做了构建引擎的切换， 属于较大的 breaking change。官网的关于remix的引入描述主要针对 remix v1，这块目前还没有精力去做跟进，可以先尝试按普通 vite工程的方式去配置。

**Comment by abstain23** [comment]
请问啥时候能支持呢

**Comment by pointhalo** [comment]
> 请问啥时候能支持呢

暂时没有明确的推进计划。在工程化能力上，Semi 对 Webpack、Rspack、常规 Vite工程属于第一梯队兼容，基本不会遇到什么问题，同时我们也会定期 follow 相关构建工具的一些新feature 进化。
但是对于 Remix 而言，它在构建配置上自己有很多黑盒型的魔改行为，并且经常性地产生一些不兼容的 breaking change，我们排查问题起来成本非常高。这类问题对我们来说优先级不是那么高。
以及按照他们的 roadmap，下一个大版本又要跟 react-router做品牌融合，整体规划其实不太明确，我们目前不倾向于对中间态的版本投入过多时间。

**Comment by pointhalo** [comment]
如果不需要配置Semi 主题，仅使用默认主题样式的话，尝试一下这个配置，在 remix 2.12 上实测是ok的。

```
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      "date-fns-tz": path.resolve(
        __dirname,
        "node_modules/date-fns-tz/esm/index.js"
      ),
    },
  },
  ssr: {
    noExternal: [
      "@douyinfe/semi-ui",
      "@douyinfe/semi-foundation",
      "@douyinfe/semi-illustrations",
      "@douyinfe/semi-icons",
      "scroll-into-view-if-needed",
    ],
  },
  plugins: [
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
});
```
