### ISSUE TITLE
[BUG] Table+virtualized在快速切换下会触发 Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops

### ISSUE THREAD

**Issue by xmsz-stu** [DouyinFE/semi-design#2592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Table

### Semi Version

2.69.2

### Current Behavior

快速切换页面，重新赋值数据源，有高概率触发
```
react-dom.development.js:27331 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27331:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25514:1)
    at Object.enqueueSetState (react-dom.development.js:17925:1)
    at push.../../node_modules/.pnpm/react@18.3.1/node_modules/react/cjs/react.development.js.Component.setState (react.development.js:354:1)
    at Object.setVirtualizedData (index.js:509:1)
    at TableBodyFoundation.initVirtualizedData (bodyFoundation.js:18:1)
    at Body.componentDidUpdate (index.js:568:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23372:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24727:1)
    at commitLayoutEffects_begin (react-dom.development.js:24713:1)
checkForNestedUpdates	@	react-dom.development.js:27331
scheduleUpdateOnFiber	@	react-dom.development.js:25514
enqueueSetState	@	react-dom.development.js:17925
push.../../node_modules/.pnpm/react@18.3.1/node_modules/react/cjs/react.development.js.Component.setState	@	react.development.js:354
setVirtualizedData	@	index.js:509
initVirtualizedData	@	bodyFoundation.js:18
componentDidUpdate	@	index.js:568
```

如果去除virtualized则没有任何问题

我用固定的数据源测试也是会这样

### Environment

```markdown
- OS:
- browser:
```

**Comment by li-zhao-hotstar** [comment]
我也能触发这个问题，设置virtualized={false}也一样能触发，stack都是下面这样

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:19659:19)
    at scheduleUpdateOnFiber (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:18533:11)
    at Object.enqueueSetState (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:13467:15)
    at Component.setState (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-OU5AQDZK.js?v=bc93704b:229:24)
    at Object.setAllDisabledRowKeys (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=1cb17436:91953:14)
    at _TableFoundation.setAllDisabledRowKeys (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=1cb17436:88385:19)
    at Table.componentDidUpdate (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=1cb17436:92890:23)
    at commitLayoutEffectOnFiber (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:17053:36)
    at commitLayoutMountEffects_complete (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:17980:17)
    at commitLayoutEffects_begin (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:17969:15)
```

简单断点debug了一下，在[这行](https://github.com/DouyinFE/semi-design/blob/ccb86aeffbd3ba889df31ba7c556c36ac956b6dd/packages/semi-ui/table/Table.tsx#L590)判断，

```
if (dataSource !== prevProps.dataSource || stateCachedColumns !== prevState.cachedColumns || stateCachedChildren !== prevState.cachedChildren) {
```

里面的 stateCachedColumns !== prevState.cachedColumns 始终是true，导致了循环更新

<img width="545" alt="Screenshot 2024-12-06 at 14 06 31" src="https://github.com/user-attachments/assets/85fa8ede-bc48-44e6-8bb2-ed412488e4f8">

**Comment by shijiatongxue** [comment]
> 我也能触发这个问题，设置virtualized={false}也一样能触发，stack都是下面这样
> 
> ```
> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
>     at checkForNestedUpdates (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:19659:19)
>     at scheduleUpdateOnFiber (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:18533:11)
>     at Object.enqueueSetState (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:13467:15)
>     at Component.setState (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-OU5AQDZK.js?v=bc93704b:229:24)
>     at Object.setAllDisabledRowKeys (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=1cb17436:91953:14)
>     at _TableFoundation.setAllDisabledRowKeys (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=1cb17436:88385:19)
>     at Table.componentDidUpdate (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=1cb17436:92890:23)
>     at commitLayoutEffectOnFiber (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:17053:36)
>     at commitLayoutMountEffects_complete (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:17980:17)
>     at commitLayoutEffects_begin (http://local.hotstar-labs.com:5174/node_modules/.vite/deps/chunk-3IHV7RO6.js?v=bc93704b:17969:15)
> ```
> 
> 简单断点debug了一下，在[这行](https://github.com/DouyinFE/semi-design/blob/ccb86aeffbd3ba889df31ba7c556c36ac956b6dd/packages/semi-ui/table/Table.tsx#L590)判断，
> 
> ```
> if (dataSource !== prevProps.dataSource || stateCachedColumns !== prevState.cachedColumns || stateCachedChildren !== prevState.cachedChildren) {
> ```
> 
> 里面的 stateCachedColumns !== prevState.cachedColumns 始终是true，导致了循环更新
> 
> <img alt="Screenshot 2024-12-06 at 14 06 31" width="545" src="https://private-user-images.githubusercontent.com/52025796/393118927-85fa8ede-bc48-44e6-8bb2-ed412488e4f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDExOTYsIm5iZiI6MTczNDAwMDg5NiwicGF0aCI6Ii81MjAyNTc5Ni8zOTMxMTg5MjctODVmYThlZGUtYmM0OC00NGU2LThiYjItZWQ0MTI0ODhlNGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEwNTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYTM4NmYwZDIyZTUxODgyYTcyZWI2NjhlZTRjOWNlZGM0N2ViY2NkMDhlY2JkOWMxNDA1Njg1YTIxZThhOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GOQ37HKwu7dqfTRxJnvWEartvKvkxuPLQC9yCP0jOeM">

你也是用的 jsx children ？

**Comment by li-zhao-hotstar** [comment]
@shijiatongxue , I used below codes

```
          <Table dataSource={knowledgeList} pagination={pagination} loading={loading} rowKey={'id'} expandedRowRender={expandedRowRender} virtualized={false}>
            <Column title={dimensionTitleDiv} dataIndex='dimension_kv' key='dimension_kv' render={(kv) => kv ? kv : '[no group by]'}></Column>
            <Column title={'Percentage'} dataIndex='impact_percentage' key='percentage' render={percentageRender}></Column>
            <Column title={'Range'} dataIndex='prophet' key='range' render={rangeRender}></Column>
            <Column title={'Mark'} dataIndex='mark' key='mark'></Column>
            <Column title={'From Data'} dataIndex='' key='from' render={fromRender}></Column>
          </Table>
```
