### ISSUE TITLE
在Remix框架下用不了

### ISSUE THREAD

**Issue by jesse996** [DouyinFE/semi-design#485]
rt，remix.run这个框架用不了

**Comment by pointhalo** [comment]
any more information？error or warning？

**Comment by pointhalo** [comment]
I haven’t studied Remix in depth at the moment, but I tried to create a new project according to its official website documentation and import the Semi `Button` component into it.

#### package.json
```
  "dependencies": {
    "@douyinfe/semi-ui": "^2.2.2",
    "@remix-run/react": "^1.1.1",
    "@remix-run/serve": "^1.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "remix": "^1.1.1"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.1.1",
    "@types/react": "^17.0.24",
    "@types/react-dom": "^17.0.9",
    "typescript": "^4.1.2"
  },
```

Then when I executed `npm run dev`, I got the following error

```
/Users/Workspace/my-remix-app/node_modules/@douyinfe/semi-ui/lib/cjs/_base/base.css:5
body .semi-always-light {
                        ^
SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```
I did a related search in its issue, and it seems that it does not support importing css under a node_modules, similar feedback can be found:
1、https://github.com/remix-run/remix/issues/185
2、https://github.com/remix-run/remix/issues/108
3、https://github.com/remix-run/remix/issues/959

We believe that this is not a problem that semi should deal with. In the component library scenario, it is a very reasonable behavior to import its own corresponding css by js, and our current directory structure organization is reasonable.

**This should be fixed by remix. Before they fix the problem, you can use umd script to bypass this problem.**

**Comment by FlatMapIO** [comment]
Remix  在构建集成非常固执, 除了不支持外部模块中的 css import 以外, 还不让导入外部模块中的 esm. 
我创建了 index.ts `export * from 'semi-ui'`  用 vite 将整个 semi-ui 重新 build 为一个 cjs 模块后,   在 remix 中可以正确的引用

**Comment by pointhalo** [comment]
更新：
remix在最新版本中，去除了对 node_modules 模块 import css的限制，相关配置文档已更新：https://semi.design/zh-CN/start/getting-started
按照 getting started 操作即可接入 Semi

![image](https://user-images.githubusercontent.com/88709023/213400784-bcb84862-d355-45b8-ba8d-31f57fe143e8.png)

**Comment by xmsz-stu** [comment]
> 更新： remix在最新版本中，去除了对 node_modules 模块 import css的限制，相关配置文档已更新：https://semi.design/zh-CN/start/getting-started 按照 getting started 操作即可接入 Semi
> 
> ![image](https://user-images.githubusercontent.com/88709023/213400784-bcb84862-d355-45b8-ba8d-31f57fe143e8.png)

按照教程配置后，还是显示
```
[vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "/app/routes/kq.corp.list/route.tsx"
|- /code/m/node_modules/@douyinfe/semi-ui/lib/cjs/_base/base.css:4
body {
     ^

SyntaxError: Unexpected token '{'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/code/m/node_modules/@douyinfe/semi-ui/lib/cjs/index.js:576:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)


```
```
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  future: {
    unstable_cssSideEffectImports: true,
  },
  serverDependenciesToBundle: [
    /^@douyinfe\/semi-ui/,
    /^@douyinfe\/semi-icons/,
    /^@douyinfe\/semi-illustrations/,
  ],
};

```
```
import './tailwind.css';
import { cssBundleHref } from '@remix-run/css-bundle';
import { LinksFunction } from '@remix-run/node';
import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from '@remix-run/react';

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  return <Outlet />;
}

export const links: LinksFunction = () => {
  return [
    ...(cssBundleHref ? [{ rel: 'stylesheet', href: cssBundleHref }] : []),
    // ...
  ];
};

```

**Comment by xmsz-stu** [comment]
remix 2.x 下要如何配置？

**Comment by xmsz-stu** [comment]
remix2.0 我暂时这样写， 可以运行但不知道会遇到什么后续问题
```
import { vitePlugin as remix } from '@remix-run/dev';
import { installGlobals } from '@remix-run/node';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import { cjsInterop } from 'vite-plugin-cjs-interop';

installGlobals();

export default defineConfig({
  plugins: [
    cjsInterop({
      dependencies: ['date-fns-tz'],
    }),
    remix(),
    tsconfigPaths(),
  ],
  ssr: {
    noExternal: [
      '@douyinfe/semi-ui',
      '@douyinfe/semi-foundation',
      'scroll-into-view-if-needed',
      '@douyinfe/semi-icons',
    ],
  },
});

```

**Comment by reorx** [comment]
初始化了一个最简单的 remix 2.11.1 + semi-ui 2.63.1 项目, 使用 @xmsz-stu 配置中的 ssr.noExternal 可以工作:

`vite.config.ts`:
```
export default defineConfig({
  plugins: [
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
  ssr: {
    noExternal: [
      '@douyinfe/semi-ui',
      '@douyinfe/semi-foundation',
      '@douyinfe/semi-illustrations',
      '@douyinfe/semi-icons',
    ],
  }
});
```

**Comment by favoritewky** [comment]
> 初始化了一个最简单的 remix 2.11.1 + semi-ui 2.63.1 项目, 使用 @xmsz-stu 配置中的 ssr.noExternal 可以工作:
> 
> `vite.config.ts`:
> 
> ```
> export default defineConfig({
>   plugins: [
>     remix({
>       future: {
>         v3_fetcherPersist: true,
>         v3_relativeSplatPath: true,
>         v3_throwAbortReason: true,
>       },
>     }),
>     tsconfigPaths(),
>   ],
>   ssr: {
>     noExternal: [
>       '@douyinfe/semi-ui',
>       '@douyinfe/semi-foundation',
>       '@douyinfe/semi-illustrations',
>       '@douyinfe/semi-icons',
>     ],
>   }
> });
> ```

请问其他配置和官方的相同吗？我今天初始化发现还是有问题https://github.com/DouyinFE/semi-design/issues/2444
```
Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async nodeImport (file:///Y:/ffb/software/ffbmaster-web/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52954:15
```

**Comment by pointhalo** [comment]
Q：请问其他配置和官方的相同吗？我今天初始化发现还是有问题https://github.com/DouyinFE/semi-design/issues/2444
A： Remix v2在编译工具的选择上有两种构建器，经典构建器和vite构建器，如果你使用的是 vite构建器，尝试以下配置

  - date-fns-tz 通过 alias 指向它的 esm版本，否则它可能会报 “Cannot use import statement outside a module” 的错误
  - 通过 ssr.noExternal 指定 Semi 相关的包名 + scroll-into-view-if-needed （底层依赖），否则会有css无法正确处理的问题
```
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      "date-fns-tz": path.resolve(
        __dirname,
        "node_modules/date-fns-tz/esm/index.js"
      ),
    },
  },
  ssr: {
    noExternal: [
      "@douyinfe/semi-ui",
      "@douyinfe/semi-foundation",
      "@douyinfe/semi-illustrations",
      "@douyinfe/semi-icons",
      "scroll-into-view-if-needed",
    ],
  },
  plugins: [
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
});
```
