### ISSUE TITLE
Navigation#JSX 写法 Nav.Sub  Cannot read properties of null (reading 'getCurrentStates')

### ISSUE THREAD

**Issue by JmmBite** [DouyinFE/semi-design#795]
### Which Component 出现bug的组件
  - Navigation

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
```
Animation.js:174 Uncaught TypeError: Cannot read properties of null (reading 'getCurrentStates')

    at Animation2.render (Animation.js:174:38)
    at finishClassComponent (react-dom.development.js:20487:31)
    at updateClassComponent (react-dom.development.js:20433:24)
    at beginWork (react-dom.development.js:22366:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4157:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:16)
    at invokeGuardedCallback (react-dom.development.js:4270:31)
    at beginWork$1 (react-dom.development.js:27243:7)
    at performUnitOfWork (react-dom.development.js:26392:12)
    at workLoopSync (react-dom.development.js:26303:5)

react-dom.development.js:18525 The above error occurred in the <Animation2> component:

    at Animation2 (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:19687:5)
    at Transition (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:19964:5)
    at OpenIconTransition (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:69454:66)
    at i
    at div
    at div
    at li
    at NavItem2 (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:69146:5)
    at SubNav (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:69500:5)
    at ul
    at div
    at div
    at div
    at div
    at LocaleConsumer (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:46016:22)
    at Nav (http://localhost:3011/node_modules/.vite/deps/@douyinfe_semi-ui.js?v=8faf2496:70013:5)
    at NavApp (http://localhost:3011/src/NavApp.tsx?t=1650944095304:6:16)
    at App
    at Router (http://localhost:3011/node_modules/.vite/deps/react-router-dom.js?v=8faf2496:1065:15)
    at BrowserRouter (http://localhost:3011/node_modules/.vite/deps/react-router-dom.js?v=8faf2496:1194:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

react-dom.development.js:11996 Uncaught TypeError: Cannot read properties of null (reading 'getCurrentStates')
    at Animation2.render (Animation.js:174:38)
    at finishClassComponent (react-dom.development.js:20487:31)
    at updateClassComponent (react-dom.development.js:20433:24)
    at beginWork (react-dom.development.js:22366:16)
    at beginWork$1 (react-dom.development.js:27219:14)
    at performUnitOfWork (react-dom.development.js:26392:12)
    at workLoopSync (react-dom.development.js:26303:5)
    at renderRootSync (react-dom.development.js:26271:7)
    at recoverFromConcurrentError (react-dom.development.js:25689:20)
    at performSyncWorkOnRoot (react-dom.development.js:25935:20)
```

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - https://semi.design/zh-CN/navigation/navigation#jsx-写法

### Reproducible code 复现代码
```
import React from 'react';
import { Nav } from '@douyinfe/semi-ui';
import { IconStar, IconUser, IconUserGroup } from '@douyinfe/semi-icons';

class NavApp extends React.Component {
    render() {
        return (
            <Nav
                bodyStyle={{ height: 320 }}
                defaultOpenKeys={['user', 'union']}
                onSelect={data => console.log('trigger onSelect: ', data)}
                onClick={data => console.log('trigger onClick: ', data)}
            >
                <Nav.Header logo={<img src="https://sf6-cdn-tos.douyinstatic.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/webcast_logo.svg" />} text={'Semi 运营后台'} />
                <Nav.Item itemKey={'union'} text={'公会中心'} icon={<IconStar />} />
                <Nav.Sub itemKey={'user'} text="用户管理" icon={<IconUser />}>
                    <Nav.Item itemKey={'golder'} text={'金主管理'} />
                    <Nav.Item itemKey={'ban'} text={'用户封禁'} />
                </Nav.Sub>
                <Nav.Footer collapseButton={true} />
            </Nav>
        );
    }
}


```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景
```
{
  "name": "react",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@douyinfe/semi-icons": "^2.9.0",
    "@douyinfe/semi-ui": "^2.9.0",
    "@loadable/component": "^5.15.2",
    "@types/node": "^17.0.26",
    "normalize.css": "^8.0.1",
    "p-min-delay": "^4.0.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.3.0"
  },
  "devDependencies": {
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^1.3.0",
    "typescript": "^4.6.3",
    "vite": "^2.9.5"
  }
}
```

**Comment by pointhalo** [comment]
与 #745 应该是同样的问题。React v18的createRoot + StrictMode会有问题（StrictMode会重复跑一些生命周期，某些副作用不可能存在问题）。建议先关掉严格模式、或者用 v17、或者用ReactDOM.render模式。

**Comment by pointhalo** [comment]
已于2.10.2-alpha.1 修复，可以试用。预计本周合入正式版
