### ISSUE TITLE
addWithInitValue 无法设置Checkbox 选中

### ISSUE THREAD

**Issue by TrumanDu** [DouyinFE/semi-design#854]
### Which Component 出现bug的组件
  - Button

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
class Demo extends React.component {

    render() {
        return (
            <Button>bug</Button>
        )
    }

}

```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

**Comment by TrumanDu** [comment]
描述错误，可以生效，只是会有异常提醒
```
react_devtools_backend.js:3973 Warning: Received `false` for a non-boolean attribute `name`.

If you want to write it to the DOM, pass a string instead: name="false" or name={value.toString()}.

If you used to conditionally omit it with name={condition && value}, pass name={condition ? value : undefined} instead.
    at input
    at span
    at CheckboxInner (http://localhost:1212/renderer.dev.js:174928:1)
    at span
    at Checkbox (http://localhost:1212/renderer.dev.js:174480:5)
    at div
    at div
    at SemiField (http://localhost:1212/renderer.dev.js:181394:98)
    at div
    at ArrayFieldComponent (http://localhost:1212/renderer.dev.js:180339:5)
    at div
    at Col (http://localhost:1212/renderer.dev.js:182544:1)
    at div
    at Row (http://localhost:1212/renderer.dev.js:182728:5)
    at form
    at Form (http://localhost:1212/renderer.dev.js:180619:5)
    at div

```

**Comment by pointhalo** [comment]
已知问题，已经在beta版中修复了。会随本周合入正式版。

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/88709023/169736619-de5ff30a-aa0d-4a46-b90e-22e26bfa3a17.png">
